[tool.poetry]
name = "gradio-sample"
version = "0.1.0"
description = ""
authors = ["ktoyod <ytdh7834@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gradio = "^3.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
